# -*- coding: utf-8 -*-
"""quantum_circuit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PsPKS0SEN6w78G4QX7Bt8hAaz4z0EjBt
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive

drive.mount("/content/drive")

# %cd "/content/drive/MyDrive/Colab Notebooks/Prior-informed DAG-GDN"

# Commented out IPython magic to ensure Python compatibility.
# %pip install -qq qiskit pylatexenc

from io import StringIO
from qiskit.circuit import ParameterVector, QuantumCircuit
from collections.abc import Sequence
import re
import numpy as np
import pandas as pd
import requests
import pylatexenc

import json
from typing import Any

import gzip
import pickle
from pathlib import Path

from difflib import get_close_matches
import warnings
import networkx as nx

import matplotlib.pyplot as plt

def load_gene_graph(
    file_path: str | Path,
) -> nx.DiGraph:
    """
    Restore a previously saved NetworkX gene-regulatory graph.
    """
    file_path = Path(file_path)

    with gzip.open(file_path, "rb") as file:
        graph = pickle.load(file)

    if not isinstance(graph, nx.DiGraph):
        raise TypeError("The saved object is not a NetworkX DiGraph.")

    return graph

def make_qubit_mapping(
    graph: nx.DiGraph,
) -> tuple[list[str], dict[str, int]]:
    """
    Create a deterministic gene-to-qubit mapping.

    Genes are ordered using a lexicographical topological sort:
    graph dependencies are respected, and alphabetical order is used
    whenever multiple genes are simultaneously available.

    Parameters
    ----------
    graph
        Gene-regulatory DAG whose nodes are gene symbols.

    Returns
    -------
    ordered_genes
        Gene symbols in deterministic topological order.
    gene_to_qubit
        Mapping from each gene symbol to its qubit index.
    """

    if not nx.is_directed_acyclic_graph(graph):
      return (None, None)

    ordered_genes = list(
        nx.lexicographical_topological_sort(graph, key=str)
    )

    gene_to_qubit = {
        gene: qubit_index
        for qubit_index, gene in enumerate(ordered_genes)
    }

    return ordered_genes, gene_to_qubit

def make_edge_schedule(
    graph: nx.DiGraph,
    ordered_genes: list[str],
) -> list[tuple[str, str]]:
    """
    Create a deterministic schedule for the graph's directed edges.

    Source genes are processed in the supplied topological order.
    For each source gene, outgoing target genes are ordered
    alphabetically.

    Parameters
    ----------
    graph
        Gene-regulatory DAG.
    ordered_genes
        Deterministic topological node order returned by
        ``make_qubit_mapping``.

    Returns
    -------
    scheduled_edges
        Ordered list of ``(source_gene, target_gene)`` tuples.
        This order will later define the CRY parameter-vector order.
    """
    scheduled_edges = []

    for source in ordered_genes:
        targets = sorted(graph.successors(source), key=str)

        for target in targets:
            scheduled_edges.append((source, target))

    return scheduled_edges

def build_parameterized_circuit(
    graph: nx.DiGraph,
    initial_values: Sequence[float] | None = None,
    rotation_axis: str = "y",
    add_measurements: bool = True,
) -> tuple[QuantumCircuit, dict]:
    """
    Build a gene-regulatory quantum circuit with fixed initial angles
    and trainable edge angles.

    Every gene is represented by one qubit. Each qubit first receives
    a fixed single-qubit rotation. Each directed graph edge is then
    represented by a parameterized controlled rotation.

    The selected rotation axis is used consistently:

        rotation_axis="x" -> RX and CRX gates
        rotation_axis="y" -> RY and CRY gates

    Parameters
    ----------
    graph
        Gene-regulatory DAG whose nodes are gene symbols.

    initial_values
        Fixed initial rotation angles. Their order corresponds to
        ``ordered_genes`` and therefore to qubit order.

    rotation_axis
        Rotation family used throughout the circuit. Must be "x" or "y".

    Returns
    -------
    circuit
        Qiskit circuit whose only free parameters are the edge angles.

    metadata
        Dictionary containing the qubit mapping, edge schedule,
        fixed initial values, and trainable edge parameters.
    """
    rotation_axis = rotation_axis.lower()

    if rotation_axis not in {"x", "y"}:
        raise ValueError("rotation_axis must be either 'x' or 'y'.")

    ordered_genes, gene_to_qubit = make_qubit_mapping(graph)

    if initial_values is None:
        initial_values = (0.0,) * len(ordered_genes)
    elif len(initial_values) != len(ordered_genes):
        raise ValueError(
            "The number of initial values must equal the number of genes."
        )
    else:
        initial_values = tuple(initial_values)

    scheduled_edges = make_edge_schedule(
        graph,
        ordered_genes,
    )

    edge_angles = ParameterVector(
        "edge_angle",
        len(scheduled_edges),
    )

    circuit = QuantumCircuit(
        len(ordered_genes),
        name=f"gene_dag_{rotation_axis}",
    )

    if rotation_axis == "x":
        initial_rotation = circuit.rx
        controlled_rotation = circuit.crx
    else:
        initial_rotation = circuit.ry
        controlled_rotation = circuit.cry

    # Fixed initial rotations.
    for qubit, initial_angle in enumerate(initial_values):
        initial_rotation(initial_angle, qubit)

    # Trainable controlled rotations representing regulatory edges.
    for edge_index, (source, target) in enumerate(scheduled_edges):
        control_qubit = gene_to_qubit[source]
        target_qubit = gene_to_qubit[target]

        controlled_rotation(
            edge_angles[edge_index],
            control_qubit,
            target_qubit,
        )

    if add_measurements:
        circuit.measure_all()

    gene_to_initial_value = {
        gene: initial_values[gene_to_qubit[gene]]
        for gene in ordered_genes
    }

    edge_to_angle = {
        edge: edge_angles[edge_index]
        for edge_index, edge in enumerate(scheduled_edges)
    }

    metadata = {
        "rotation_axis": rotation_axis,
        "ordered_genes": ordered_genes,
        "gene_to_qubit": gene_to_qubit,
        "scheduled_edges": scheduled_edges,
        "initial_values": initial_values,
        "gene_to_initial_value": gene_to_initial_value,
        "edge_angles": edge_angles,
        "edge_to_angle": edge_to_angle,
    }

    return circuit, metadata

def assign_edge_parameters(
    circuit: QuantumCircuit,
    edge_angles: ParameterVector,
    edge_values: Sequence[float],
) -> QuantumCircuit:
    """
    Assign numerical values to the trainable edge parameters.

    Parameters
    ----------
    circuit
        Parameterized gene-regulatory circuit.

    edge_angles
        Edge ParameterVector created by the circuit builder.

    edge_values
        Numerical edge angles in scheduled-edge order.

    Returns
    -------
    QuantumCircuit
        A copy of the circuit with all edge parameters assigned.
    """
    if len(edge_values) != len(edge_angles):
        raise ValueError(
            "The number of edge values must equal the number "
            "of edge parameters."
        )

    parameter_map = {
        parameter: value
        for parameter, value in zip(edge_angles, edge_values)
    }

    return circuit.assign_parameters(
        parameter_map,
        inplace=False,
    )

def align_bitstring(
    bitstring: str,
    ordered_genes: list[str],
) -> str:
    """
    Reverse a Qiskit output bitstring so its positions correspond
    directly to ordered_genes.
    """
    if len(bitstring) != len(ordered_genes):
        raise ValueError(
            "The bitstring length must equal the number of ordered genes."
        )

    return bitstring[::-1]

def metadata_to_serializable(
    metadata: dict[str, Any],
    include_initial_values: bool = True,
) -> dict[str, Any]:
    """
    Convert circuit metadata into a JSON-serializable dictionary.

    Parameters
    ----------
    metadata
        Circuit metadata produced during graph or circuit preparation.

    include_initial_values
        Whether to include fixed initial rotation values when available.

    Returns
    -------
    dict
        Minimal JSON-serializable metadata.
    """
    serializable = {
        "ordered_genes": list(metadata["ordered_genes"]),
        "scheduled_edges": [
            list(edge)
            for edge in metadata["scheduled_edges"]
        ],
    }

    # These fields may not exist if metadata is saved before
    # full circuit construction.
    if "rotation_axis" in metadata:
        serializable["rotation_axis"] = metadata["rotation_axis"]

    if "add_measurements" in metadata:
        serializable["add_measurements"] = metadata["add_measurements"]

    if (
        include_initial_values
        and metadata.get("initial_values") is not None
    ):
        serializable["initial_values"] = [
            float(value)
            for value in metadata["initial_values"]
        ]

    return serializable


def save_circuit_metadata(
    metadata: dict[str, Any],
    file_path: str | Path,
    include_initial_values: bool = True,
) -> None:
    """
    Save circuit metadata to a JSON file.
    """
    serializable = metadata_to_serializable(
        metadata,
        include_initial_values=include_initial_values,
    )

    with open(file_path, "w", encoding="utf-8") as file:
        json.dump(
            serializable,
            file,
            indent=2,
        )


def load_circuit_metadata(
    file_path: str | Path,
) -> dict[str, Any]:
    """
    Load circuit metadata from a JSON file.

    Scheduled edges are restored as tuples. Initial values remain
    optional and are restored as a tuple when present.
    """
    with open(file_path, "r", encoding="utf-8") as file:
        metadata = json.load(file)

    metadata["scheduled_edges"] = [
        tuple(edge)
        for edge in metadata["scheduled_edges"]
    ]

    if "initial_values" in metadata:
        metadata["initial_values"] = tuple(
            metadata["initial_values"]
        )

    return metadata

dag_graph = load_gene_graph(
    "selected_gene_dag.pkl.gz",
)

print(dag_graph.number_of_nodes())
print(dag_graph.number_of_edges())
print("Is DAG:", nx.is_directed_acyclic_graph(dag_graph))

circuit, circuit_metadata = build_parameterized_circuit(
    dag_graph,
    rotation_axis="y",
)

print(circuit_metadata["gene_to_qubit"])
print(circuit_metadata["gene_to_initial_value"])
print(circuit_metadata["edge_to_angle"])

rng = np.random.default_rng(seed=42)

current_edge_values = rng.uniform(
    low=-0.01 * np.pi,
    high=0.01 * np.pi,
    size=len(circuit_metadata["edge_angles"]),
)

bound_circuit = assign_edge_parameters(
    circuit,
    circuit_metadata["edge_angles"],
    current_edge_values,
)

save_circuit_metadata(
    circuit_metadata,
    "gene_circuit_structure.json",
    include_initial_values=False,
)

bound_circuit.draw("mpl")